### PR TITLE
add file

### PR DESCRIPTION
**Pull request by JediMasterSoda**

### CODE REVIEW

**Comment by JediMasterSoda** [comment]
maRYCd0

**Comment by CVunderscore** [comment]
r_1100505_X2X2H

**Comment by CVunderscore** [comment]
images

**Comment by CVunderscore** [comment]
3-billion-devices-run-java-and-other-hilarious-jokes-you-32425656

**Comment by JediMasterSoda** [comment]
stackoverflow

**Comment by CVunderscore** [comment]
nebraska2013-mayjune

**Comment by CVunderscore** [comment]
8jasv4moium31

**Pull request merged**
